services:
  - type: web
    name: flask-backend
    env: python
    plan: free
    branch: main
    rootDirectory: backend
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
